### ISSUE TITLE
`babel` related packages should be included in `devDependencies`

### ISSUE THREAD

**Issue by JounQin** [webpack-contrib/webpack-hot-client#1]
* Operating System: macOS 10.12
* Node Version: v9.3.0
* NPM Version: 5.6.0
* webpack Version: 3.10.0
* webpack-dev-server Version: none

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Expected Behavior

Run well with babel 7, `@babel/preset-env`,etc

### Actual Behavior
```bash
Error: Couldn't find preset "@babel/env" relative to directory "/local/GitHub/react-hackernews"
```

### For Features; What is the motivation and/or use-case for the feature?
`babel` is not needed after published for this module.

**Comment by shellscape** [comment]
That's not actually correct. They have to be in regular dependencies due to needed compilation of the client scripts at runtime when included in a bundle.

**Comment by JounQin** [comment]
@shellscape But it can not works with babel@7 as I mentioned above, why not add a build step before publishing instead of building at runtime?

**Comment by shellscape** [comment]
I'm open to a PR outlining what that pipeline would look like. The important bit is that the client script has to be added to webpack in the manner it currently is to ensure proper bundling and injection of the options.

I'm also curious about the issues with babel@7. Would you be up for telling me more?

**Comment by JounQin** [comment]
It seems related to `babel-cli`, which will register another `babel-node` bin and overwrite `@babel/node`'s.

**Comment by lutangar** [comment]
Hey guys, 

I'm also having troubles with the runtime build thing:
`Module build failed: Error: Cannot find module 'babel-preset-env' from '...'`

Plus I wouldn't mind adding an `entry` to my webpack config manually. Many packages are doing it this way... might be even cleaner not to *mess* with the user's webpack config anyway?

**Comment by shellscape** [comment]
@lutangar we're not _messing_ with the users config. we're just telling the compiler to toss in another file. The user's config is intact. That's a design decision I'm firm on. We're currently exploring some options on the babel thing. Follow the repo for updates on that front.

**Comment by lutangar** [comment]
Alright, either way, I wouldn't mind.
