### ISSUE TITLE
"TypeError: Converting circular structure to JSON" thrown at init when passing in a server instance

### ISSUE THREAD

**Issue by twelve17** [webpack-contrib/webpack-hot-client#15]
* Operating System: Mac OS X
* Node Version: 8.9.4
* NPM Version: 5.6.0
* webpack Version: webpack@3.10.0
* webpack-dev-server Version: N/A (see explanation in "How to Reproduce")

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

This can be reproduced using the `webpack-hot-client` project itself.  Refer to the "How to Reproduce" section.

### Expected Behavior

`webpack-hot-client` should initialize without an error when supplying a Koa `server` instance, as the docs mention `Koa` as a valid source to provide a server instance.

### Actual Behavior

`webpack-hot-client` throws this error:

```
    TypeError: Converting circular structure to JSON
      at JSON.stringify (<anonymous>)
      at modifyCompiler (/Volumes/foo/work/webpack-hot-client/lib/util.js:7:95)
      at module.exports (/Volumes/foo/work/webpack-hot-client/index.js:3:157)
      at Context.it (/Volumes/foo/work/webpack-hot-client/test/tests/init.js:47:23)
```

### For Bugs; How can we reproduce the behavior?

I've been able to reproduce this error with the `webpack-hot-client` project itself.

1. Clone the `webpack-hot-client` repo.  I tested with the project at revision `cfca82eb1e1`.
2. Install `koa`:
  ```
  npm i koa@2.4.1
  ```
3. Add a new test to `test/tests/init.js`, to test this scenario:
  ```
  const Koa = require('koa');

  it('should allow passing koa server instance', () => {
    const app = new Koa();
    const server = app.listen(8081);
    const config = require('../fixtures/webpack.config.js');
    const compiler = webpack(config);
    const options = { hot: true, logLevel: 'info', test: true, server: server };
    const { close } = client(compiler, options);
    assert(true);
  });
  ```

**Comment by shellscape** [comment]
@twelve17 thanks for the issue. can you verify you're using the latest copy of `master`? the line numbers in your stack trace aren't lining up with what I'm seeing in code on my end.

**Comment by shellscape** [comment]
That commit is moot. Wonky travis-ci issues, so rolling back and will resolve on a branch.

**Comment by twelve17** [comment]
Thanks for doing this so quickly!
