### ISSUE TITLE
docs: Difference with Webpack Hot Middleware

### ISSUE THREAD

**Issue by dlmr** [webpack-contrib/webpack-hot-client#18]
- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

_Hi, I have gone away from the template a little to make it more clear, feel free to close if it was out of line._

### Difference with Webpack Hot Middleware

Would be nice if the documentation could state what the difference between this project and [Webpack Hot Middleware](https://github.com/glenjamin/webpack-hot-middleware). Does not need to be a list of features or anything like that, could just be the goals of this project made clear. My assumption is that this will be recommended way going forward since it's part of the `webpack-contrib` organization but maybe they both are good alternatives for different use cases.

**Comment by shellscape** [comment]
I suppose we could be a section in there to explicitly address that. Well the important bits are at the top:

> webpack-hot-client accomplishes this by creating a WebSocket server, providing the necessary client (browser) scripts that communicate via WebSockets, and automagically adding the necessary webpack plugins and config entries. All of that allows for a seamless integration of Hot Module Support.

And [https://github.com/webpack-contrib/webpack-hot-client#browser-support](https://github.com/webpack-contrib/webpack-hot-client#browser-support). 

`webpack-hot-middleware` supports ancient browsers via a client/serve communication technique that has support going back to early IE, whereas this module uses `WebSockets`. Our technique is faster and more flexible, but the browser support requires newer versions. Folks that have to support old browsers or browsers that haven't implemented `WebSockets` won't be able to use this `hot-client`. The other big different is that `hot-middleware` is middleware and it requires a server that uses express-style middleware patterns. On the flip side, `hot-client` is *not* middleware and can be run in tandem with any server kind. Thought that's kind of moot if using `webpack-dev-middleware`, which is the most likely scenario. 

The final difference comes from this line:

> Reminder: You don't have to modify your config at all!

`hot-middleware` requires users to modify their config to use it. Webpack as an org is trying to move away from making users do extra lifting, and `hot-client` follows that mantra by automatically inserting plugins and entry scripts into a compilation for the user. It's a more seamless experience.

**Comment by dlmr** [comment]
Great answer, thanks!

While it might be smart to make some of these things clearer in the documentation I now think it's good enough to have this issue here as a form of documentation that can be referenced and found if someone has the same questions as I. 🙂 

Given that I will go ahead and close this issue, please reopen if you want to use it for tracking an intended change. 👍

**Comment by shellscape** [comment]
Thanks for raising a solid question. I'll update the README to point to this issue for that particular question.
