### ISSUE TITLE
it seems reload not working while ignored an update to unaccepted module

### ISSUE THREAD

**Issue by Jokcy** [webpack-contrib/webpack-hot-client#21]
Just read a little bit code of webpack-hot-client, in `lib/client/hot.js`, unaccepted module has been handled like this:
```
onUnaccepted(data) {
    const chain = [].concat(data.chain);
    const last = chain[chain.length - 1];

    if (last === 0) {
      chain.pop();
    }

    log.warn(`Ignored an update to unaccepted module ${chain.join(' ➭ ')}`);
 }
```
just warnings no refresh. and what I saw in my project is no refresh.
I suppose there should be a refresh here for:
> If true, instructs the browser to physically refresh the entire page if / when
webpack indicates that a hot patch cannot be applied and a full refresh is needed. 

or maybe I can do a pull request.

sorry for my poor english😄

**Comment by shellscape** [comment]
From the issue template:

> Please note that this template is not optional.
  Please fill out _ALL_ fields, or your issue may be closed as "invalid."
  Please do not delete this template.

**Comment by Jokcy** [comment]
@shellscape I don't know whether you had read the issue and the pr. so I am confused that if I try again with valid template, will it be pass?
