### ISSUE TITLE
Allow specifying client "server host" independently (from server "host")

### ISSUE THREAD

**Issue by nmschulte** [webpack-contrib/webpack-hot-client#29]
It's conceivable that the client will be configured to connect to the server via a different host/port.  This can be accommodated with minimal code change, simply by allowing to specify a different host/port for the client.

For example, imagine the server (`webpack-hot-client`, and thus `webpack` proper) is running on a hypervisor guest ("inside a virtual machine"; Vagrant, etc.), or contained inside an LXC container (Docker), or behind a reverse proxy, or even on a remote machine.  As it stands, the codes assume the client environment is the same as the server and forces the use of the server options (https://github.com/webpack-contrib/webpack-hot-client/blob/master/index.js#L55).

Trivially, this could be done by allowing a `webSocket.host`/`webSocket.port` `option` (https://github.com/webpack-contrib/webpack-hot-client#clientcompiler-options).  This could be improved/normalized however appropriate.

Less trivially, and more generally, the codes could check for a `webpack-hot-client/client` entry before augmenting and skip the step if it exists.  This would allow a user-in-the-know to manually configure all of the client options (if I understand the code correctly, that is).

My particular use-case is "containerized build via Docker," and using `0.0.0.0` as the `host` option gets me what I need, but is a real hack (as the client connects to the socket on `ws://0.0.0.0`, and `0.0.0.0` is not required to resolve, though implementations tend to allow it: https://unix.stackexchange.com/questions/419880/connecting-to-ip-0-0-0-0-succeeds-how-why)

**Comment by shellscape** [comment]
😆 I mean come on, the instructions are literally the first three lines of the issue template.

**Comment by nmschulte** [comment]
This is the funny part: I blindly followed the template, and upon reaching the end and realizing that all of the information is irrelevant deleted all the hard work.  Of course, my assumption that you're only planning to support one release at a time (v2) may be wrong, and you're accepting feature requests for v1 still.

See #30 for a non template-removed version.

**Comment by shellscape** [comment]
👍 next time use that edit button and send a ping and we'll just reopen.
