### ISSUE TITLE
Can't read log output on dark theme Chrome or FireFox because the font color isn't high contrast

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/webpack-hot-client#33]
* Operating System: Darwin 17.4.0
* Node Version: 9.5.0
* NPM Version 5.6.0
* webpack Version 4.1.1
* webpack-hot-client Version: 1.3.0

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

See https://github.com/joshunger/bugrepro

### Expected Behavior
A user can read the logs.

### Actual Behavior
Can't read the logs because of the text color.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/2301847/37612014-950f325a-2b69-11e8-971b-06b76a1f34a2.png">

### For Bugs; How can we reproduce the behavior?

Clone https://github.com/joshunger/bugrepro

```bash
cd bugrepro
yarn
yarn start
```
Open browser.
Change devtools to Dark Theme in Chrome or FireFox.
Load URL.

**Comment by joshunger** [comment]
@nchevobbe

**Comment by joshunger** [comment]
@shellscape assign to me and I'll send you a PR.  I just need the info from Chrome folks.

**Comment by joshunger** [comment]
@garbee can you help on the Chrome side?

**Comment by joshunger** [comment]
@shellscape can I just remove?  Why was it there originally?

**Comment by Garbee** [comment]
I'm not sure what Chrome/FF in particular have to do here. This is about the color contrast as styled by the application, not something done by default by the browsers.

If there is a specific console statement that is difficult to read by default, then please file bugs on the appropriate tool's issue tracker. That would mean the problem is reproducible by simply running a certain `console.log` statement for example manually in the terminal.

**Comment by shellscape** [comment]
With the way that css works in the browser consoles, you need to reset the color back to something. So we're going to have to figure out how to detect when contrast is needed, or what the system css variables are on each. Detecting high contrast situations would probably be preferable, though.

**Comment by Garbee** [comment]
With JS in Chrome you can check `chrome.devtools.panels.themeName` for either `default` or `dark` options to know which mode the user has selected. This however, only works with the built in themes, not any custom themes users may have enabled using the experimental flag for custom ones. I think with Firefox you just check for the dark mode class on the html or body node.

**Comment by shellscape** [comment]
OK so that's two relatively reasonable detection methods. We can then consider custom themes to be edge-cases, and users can request that similar "dark mode" classes be added to the root node(s) by the theme authors.

**Comment by Garbee** [comment]
Custom themes can't modify the node classes. Custom themes are an edge-case where we literally can't directly support it. Unless there is a set css var that is looked for first which is never set internally. Then the internal variable is the fallback. i.e. `color: var(--global-check, --internal-color)` This would look for the `--global-check` variable initially, and if set use that. Which a custom theme author would need to know about and write the variable for. If it is not set, then the `--internal-color` variable is used which is our set var in this system.

**Comment by joshunger** [comment]
Thanks for the help @Garbee happy 🌮 Thursday @shellscape if you want to assign to me I'll add it to my PR list.

**Comment by shellscape** [comment]
Will do.

**Comment by joshunger** [comment]
I'll take this next week. 👍

**Comment by shellscape** [comment]
@joshunger any action on this? if it's on the back burner, we'd rather close and get it off the books, and re-open when it can be circled back to.

**Comment by joshunger** [comment]
Feel free to close it.
