### ISSUE TITLE
TypeScript Error.

### ISSUE THREAD

**Issue by Manu-shukla** [webpack-contrib/webpack-hot-client#40]
* Operating System: Windows
* Node Version:9.0.0
* NPM Version:5.0.0
* webpack Version:2.2
* webpack-hot-client Version:

- [ x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

**Comment by shellscape** [comment]
I'm not even sure where to start with this one. You didn't fill in anything, so your issue is invalid.
