### ISSUE TITLE
Readme example of passing a `server`

### ISSUE THREAD

**Issue by leebenson** [webpack-contrib/webpack-hot-client#41]
- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

I'm attempting to set config options for webpack-hot-client in `koa-webpack`.

It'd be useful to see an example in the readme of passing in a `server` object, so that the WebSockets port used can sync with the main HTTP server.

There are two things that are unclear from the current readme.

1. Should `server` be an instance of Express/Koa, or the instance returned by Node's `http.createServer()`?

2. If it's the latter (and it seems to be, given the calls to `.address().address/port` [here](https://github.com/webpack-contrib/webpack-hot-client/blob/0d8707da129cdb6d9b892603c330f4dd2eac829f/index.js#L70), then how should a `server` object be passed to Express/Koa middleware _before_ the server has been created, either by a call to `koa.listen()` or by creating a separate server with `http.createServer(koa.callback())`?

My suggestion is therefore is to either:

a) Add an example to the readme to show how this can be done manually

or (and this is probably an issue for `koa-webpack`, but I'll suggest it here for now to avoid redundancy)

b) Automatically set the `server` option when using `koa-webpack`, since that's more likely to be able to set it automatically through the Koa `ctx` object.

I apologise in advance if I'm missing anything obvious - on initial glance, this seems to be a circular dependency (middleware needs a server, but the server won't be created until the middleware has already been set up) that the readme doesn't address.

**Comment by shellscape** [comment]
Thanks for the issue. In the future please do not remove any parts of an issue template. Doing so will trigger one of the poop-naughty labels.

> Should server be an instance of Express/Koa, or the instance returned by Node's http.createServer()?

 It's actually any instance of [`http.Server`](https://nodejs.org/api/http.html#http_class_http_server), which can be created in a myriad of ways. Both Express, Koa, and the result of http.createServer all return a result derived from that base class. I'll accept a PR that shed some more clarity to the docs, but it should not recommend one server instance over another, rather let users know they can use just about any server that derives from `http.Server`. This is one of those situations where, if a user is going to make use of an advanced-style options, they should have some understanding of what they're doing.

> a) Add an example to the readme to show how this can be done manually

Happy to review a PR for this.

> b) Automatically set the server option when using koa-webpack, since that's more likely to be able to set it automatically through the Koa ctx object.

That is a grand assumption, and best left up the user. Implementing that would be adding a large amount of complexity due to the decision tree you'd be taking on.

**Comment by leebenson** [comment]
Apologies for removing the template- I appreciate it streamlines submissions, but also didn't want to clutter the post with my environment details/code blocks that seemed superfluous to the feature request.

For some background -

I'm using `koa-webpack` in my [launch.js framework](https://github.com/launchjs/app), currently [like so](https://github.com/launchjs/app/blob/master/src/app.ts#L277-L279)

This is spawning the WS server on the default port 8081; explicitly setting `hot: { port }` to match my main HTTP server is causing a 426 response code, since it looks like WS is conflicting with the port. I'm trying to get the two working nicely together.

Additionally, my Travis build is failing when testing this out, because several of my Jest tests spawn the server, and the WS server isn't getting properly closed when the main server closes. Jest has a problem when running on a single worker thread, in that asynchronous/left-over resources are properly closed.

Based on the above, it looks like it might be neater to orchestrate `webpack-hot-client` separately, manually attach to the server, and then provide some kind of wrapper class around both the return `http.Server.close()` method and `close()` returned by hot-client, so they can both be cleaned up in tandem.

I realise that's outside the scope of this issue, but just giving a use-case on how I came across the need to sync up the http + WS server.

**Comment by leebenson** [comment]
Follow-up: I was able to get this working [as shown here](https://github.com/launchjs/app/blob/master/src/app.ts#L320-L356) -- by listening to the server first, and _then_ adding the hot client as middleware (via koa-webpack) afterwards. I wasn't sure whether Koa would essentially 'freeze' middleware after the point the listener has started; apparently not, which enables this technique.

There's a very minor race condition in this scenario, since technically the Koa server listens for incoming connections before it builds the bundle via Webpack, and attaches itself as middleware... but if (as in my case) you're awaiting a Promise or an event being emitted to signal that the server has finished its setup, then it's probably negligible.

**Comment by shellscape** [comment]
> Happy to review a PR for this.

Would still totally dig a PR for improving the documentation

**Comment by leebenson** [comment]
done - #44
