### ISSUE TITLE
Error output in browser contains ANSI escape codes

### ISSUE THREAD

**Issue by mcjfunk** [webpack-contrib/webpack-hot-client#46]
* Operating System: MacOS Sierra
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.5.0
* webpack-hot-client Version: 2.2.2

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code

I've been witnessing this with a more complex setup, but just created a simple usecase:
https://github.com/mcjfunk/hot-output-issue

### Expected Behavior

Error output in browser is legible.

### Actual Behavior

Error output contains ANSI escape codes as if for the terminal. It looks like the colors that the error uses are the culprit. They look nice in the terminal, but not the browser:

<img width="966" alt="screen shot 2018-04-16 at 8 01 53 pm" src="https://user-images.githubusercontent.com/3194796/38842706-0ee2019a-41b1-11e8-9911-a826068c0765.png">

Here's the error, in all its glory, within the mac terminal:
<img width="600" alt="screen shot 2018-04-16 at 8 16 47 pm" src="https://user-images.githubusercontent.com/3194796/38843106-26cb7852-41b3-11e8-8ba3-2e2021363ba3.png">

### For Bugs; How can we reproduce the behavior?

In the repo above...
1) run `npm start`
2) open localhost:8080 in browser
3) in `src/index.js` remove a `(` from the `ReactDOM.render` line creating a syntax error.
4) view the output in the browser

Please note, I'm not entirely sure the fix for this resides in `webpack-hot-client`. Logging takes place here, but it's unclear if cleansing the error that is delivered is its responsibility. But I thought I'd start the conversation here.

I'd love for there to be a magic config option that I've missed, but I've searched and tried many things without luck. 

Thanks!

**Comment by shellscape** [comment]
Thanks for the issue :beer: Yeah it's definitely a bug of sorts. In the hot-client code for sending an error to client sockets, it should strip ansi characters (with `strip-ansi`). Certainly inconvenient. I'll try and get a fix in tomorrow, but I'll be en route to ngconf to it totally depends on wifi aboard the plane.
