### ISSUE TITLE
Multiple bundles result in duplicate logging

### ISSUE THREAD

**Issue by mcjfunk** [webpack-contrib/webpack-hot-client#47]
Operating System: MacOS Sierra
Node Version: 8.11.1
NPM Version: 5.6.0
webpack Version: 4.5.0
webpack-hot-client Version: 2.2.2

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js (webpack 4)
     entry: {
        vendor: [
            'react',
            'react-dom'
        ]
    },
    optimization: {
        splitChunks: {
            name: 'vendor',
            minChunks: Infinity
        }
    }
    ...
```
### Expected Behavior

Browser output messages once.

### Actual Behavior

Each log line it output twice:
<img width="891" alt="screen shot 2018-04-18 at 3 08 15 pm" src="https://user-images.githubusercontent.com/3194796/38955478-6a98b7e4-431a-11e8-9d1f-1e00606fa080.png">

It gets really messy with errors. Each error is repeated twice.

I'm curious what happens with code splitting but haven't setup a test with it yet.

### For Bugs; How can we reproduce the behavior?

Setup webpack to create a vendor or common bundle, or I bet multiple entrypoints. Start things up, look at browser console.

Thanks again!

**Comment by shellscape** [comment]
Thanks for the issue :beer: sounds like we need to prefix our log messages with the chunk name for a vendor setup like that. Pretty sure we'll need a simple test repo to triage this one. (We're not all react developers :smile:)

As for the mess, not sure we can get around that. Limiting the verbosity of these messages is going to be a net loss for folks not using the same setup. You might also consider changing the log level for the client to limit it to errors.

**Comment by mcjfunk** [comment]
Thanks, @shellscape. Here's a repo that shows the issue:
https://github.com/mcjfunk/hot-duplicate-output

I created a vendor bundle and two entrypoints. This results in 3x more logging!

**Comment by shellscape** [comment]
Thanks for putting that together. FYI this likely won't result in _fewer_ log messages, as we can't control how webpack processes and reports some things, but a fix should result in more explicit log messages so you can tell what's what and from what source.

**Comment by shellscape** [comment]
FWIW the solution to #53 will fix this particular issue. I believe the causes of both are identical.
