### ISSUE TITLE
logLevel "info" too verbose

### ISSUE THREAD

**Issue by mcjfunk** [webpack-contrib/webpack-hot-client#48]
Operating System: MacOS Sierra
Node Version: 8.11.1
NPM Version: 5.6.0
webpack Version: 4.5.0
webpack-hot-client Version: 2.2.2

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### What is the motivation and/or use-case for the feature?

For application development, since the browser console is the go-to area for debugging, it is distracting to have `webpack-hot-client` to be so chatty. But by setting logLevel to "error" silences everything. Since HMR can feel like voodoo at times with the developer thinking, "did that update?", we don't want it to be completely silent.

Ideas:

**1) logLevel: "info"**
- Start up messages are currently useful 👍 
- During HMR, this lib outputs 6 lines to the console, including the modules that were updated.
- Instead, during HMR, how about one line: `｢hot｣ App updated at 3:32:13 PM`
- The timestamp becomes useful when things have updated many times, it helps distinguish updates

**2) logLevel: "debug"**
- Put those extra lines that I'm suggesting be removed from "info" here.
- It seems to me those are only useful when debugging `webpack-serve` or `webpack-hot-client`, which, once things are working, isn't very often at all.

Thanks for considering this. I'm digging these new libs and want to see them succeed.

**Comment by shellscape** [comment]
Thanks for the issue 🍺  and the kind words.

The great thing about this module is that you can have exactly that, but in user-land. You can spin up a `WebSocket` in your client code, or an accompanying dev-only module for the bundle, and listen in on the socket events that you want to report on. You can then change the default loglevel to `warn` for the client and avoid all of the messages considered to be too verbose. This could even be published to npm for reuse.

Unfortunately this module is _highly_ opinionated about what log messages are useful to the majority of users, and a lot of time and consideration was put into those decisions. I'll leave this open for discussion for a bit, but this is a changeset we're going to decline to support. Rather, we'd like to enable users to make this kinds of adjustments using what's available.

**Comment by shellscape** [comment]
We've left this open for 30 days and it hasn't received any comments, so we're going to close this one. Should it pick back up we can always reopen.
