### ISSUE TITLE
Read `window.location` for client host

### ISSUE THREAD

**Issue by Tigge** [webpack-contrib/webpack-hot-client#49]
* Operating System: Linux
* Node Version: v9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.6.0
* webpack-hot-client Version: 2.2.2

- [ ] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Code

```patch
diff --git a/lib/client/socket.js b/lib/client/socket.js
index aec287c..7182107 100644
--- a/lib/client/socket.js
+++ b/lib/client/socket.js
@@ -8,8 +8,8 @@ let retry = maxRetries;
 
 module.exports = function connect(options, handler) {
   const socketUrl = url.format({
-    protocol: options.https ? 'wss' : 'ws',
-    hostname: options.webSocket.host,
+    protocol: window.location.protocol === 'https:' ? 'wss' : 'ws',
+    hostname: window.location.hostname,
     port: options.webSocket.port,
     slashes: true
   });
```

(It should of course not look like this since the normal ways of specifying the socket url should still work. This is just to relay the idea.)

### For Features; What is the motivation and/or use-case for the feature?

Instead of having to specify the client host for the websocket server, it would be nice if it was possible to use the window.location host (and perhaps the protocol, https/http) instead of having to hardcode that before the server is run.

In some setups it is possible to access a host with many different ip addresses that are isolatet from each other. Our current setup runs the webpack hot client on the host machine and then uses multiple virtual machines running different os and web browser for testing purposes. In this setup each of the virtual machines could have a different ip address for this machine.

It would also make it easier to test this in a setup where your computer is connected to multiple networks, with multiple network cards. This is another setup that we have as well.

Is this something that you would conciser adding? If so I'll write up a better patch for this. Perhaps specifying a function to the host field or adding a new setting for this?

**Comment by shellscape** [comment]
Thanks for the issue :beer: 

Unfortunately this change won't be made. More info here: https://github.com/webpack-contrib/webpack-serve/issues/103. While this looks like a benefit on the surface, it's actually introducing complexity and limiting user ability.

**Comment by Tigge** [comment]
I can definitely understand not wanting the same feature and option creep that easily can occur if you are not strict with what you take in.

I'm a bit curious at what the platform limitations are on windows. I do think this could be helpful if it could be implemented in a good way - but yeah, perhaps the usecase is too limited.

**Comment by ezzatron** [comment]
I also have a need for this type of feature.

If the host is completely static, it's a significant pain point to have to reconfigure, and then restart my dev server manually just to demo a feature I'm working on to a colleague.

What about using a string template for the host? It would be backwards compatible, simple, and very useful for cases where people are using dynamic hosts. For example:

```js
// when server host is the same as client host
client(compiler, {host: '{host}'})

// when server host is a subdomain of the client host
client(compiler, {host: 'ws.{host}'})
```

Or, even better, would be the ability to supply a callback for building the full socket URL:

```js
client(compiler, {
  buildSocketUrl: (location, port) => {
    return url.format({
      protocol: location.protocol === 'https:' ? 'wss' : 'ws',
      hostname: location.hostname,
      port: port,
      slashes: true,
    })
  },
})
```

**Comment by shellscape** [comment]
While I understand the need and the use-case you presented, that's an excellent illustration of the kind of introduced complexity we're committed to avoiding.
