### ISSUE TITLE
Respect "host" option even when "server" is specified

### ISSUE THREAD

**Issue by cnshenj** [webpack-contrib/webpack-hot-client#50]
* Operating System: Windows 10 x64
* Node Version: 8.11.1
* NPM Version: N/A (using Yarn 1.5.1)
* webpack Version: 4.6.0
* webpack-hot-client Version: 2.2.2

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
import * as Koa from "koa";
import * as koaWebpack from "koa-webpack";
function hmr(app, server) {
    // server parameter is a Node.js https.Server instance
    app.use(koaWebpack({
        compiler,
        hot: {
            https: true,
            host: "localhost",
            // Pass in the server instance so it can be used by hot module replacement
            server,
            // Reload page if modules can't be patched
            reload: true
        } as any
    }));
}
```
### Expected Behavior
Since `server` is `https.Server`, it uses a certificate, which is tied to a host name (`localhost` in my case). However, `server.address()` returns the resolved address `127.0.0.1`. `webpack-hot-client` should use `host` option (which contains value `localhost`) in client entry code.
### Actual Behavior
The resolved address `127.0.0.1` is used in client entry code, causing this error:
```WebSocket connection to 'wss://127.0.0.1:8081/' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID```
If I manually create a secure WebSocket in browser console like this: `var wsc = new WebSocket("wss://localhost:8081")`, it works fine.
### For Bugs; How can we reproduce the behavior?
Using https.Server as the server option.

**Comment by shellscape** [comment]
Thanks for the issue :beer:

Unfortunately this won't be a change we're going to make. If `server` is specified, the hostname from that server will always be used. Such is the nature of an opinionated project. You may be able to modify the server instance you're passing to give you the desired result.
