### ISSUE TITLE
README: mention to omit the `HotModuleReplacementPlugin`

### ISSUE THREAD

**Issue by dtothefp** [webpack-contrib/webpack-hot-client#52]
* Operating System: OSX
* Node Version: 8.11.0
* NPM Version: 5.6.0
* webpack Version: 4.6.0
* webpack-hot-client Version: 2.2.2

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

#### Description
Was using the API for setting up middleware and was not seeing hot reloading and getting a maximum callstack error. I had to omit `HotModuleReplacementPlugin` from my plugins and all worked. Might be worth a mention in the README. It's great that webpack is working towards zero config, without having to add the entry scripts etc. but I had to dig through source code to see that you were already including `HotModuleReplacementPlugin`

**Comment by shellscape** [comment]
Thanks for the issue :beer: 

I'll add a note but in fairness, it doesn't instruct users to add that to their config either.
