### ISSUE TITLE
Build step to compile dist client

### ISSUE THREAD

**Issue by shellscape** [webpack-contrib/webpack-hot-client#6]
Looks like dynamic compilation, while slick, is causing more issues that it was supposed to prevent. 

Ref: https://github.com/shellscape/koa-webpack/issues/78

**Comment by lutangar** [comment]
@shellscape @JounQin are any of you started something on the build pipeline? Let me know if I can be of any help.

**Comment by shellscape** [comment]
@lutangar yep I have some stuff locally I'm toying with. much appreciate the offer to help!

**Comment by shellscape** [comment]
@lutangar @JounQin please try this branch https://github.com/webpack-contrib/webpack-hot-client/tree/babel-client-dist and let me know how it works for you. 

(we still need some client testing around this but I haven't had the opportunity to write some just yet)

**Comment by lutangar** [comment]
@shellscape as far as I'm concerned the `babel` related error is gone.
However I can't confirm that the branch is working as expected as I'm getting the following error:
```
ERROR in multi webpack-hot-client/client?main ./src/client/index.js webpack-hot-client/client
Module not found: Error: Can't resolve 'webpack-hot-client/client?main' in '...'
```

Truth to be told, I don't think it is related because I was getting the exact same error with the previous version as well.

**Comment by JounQin** [comment]
@lutangar Are you using more than one webpack compiler instance at the same time? I met the same error when I implemented SSR before, but I've fixed it through this commit https://github.com/webpack-contrib/webpack-hot-client/commit/87de9e600141c10adc05d5c4f3219bb091795884 .

**Comment by lutangar** [comment]
@jounQin didn't want to pollute this issue, I filled in a dedicated issue #8
