### ISSUE TITLE
README: client per entry vs single client per all entries

### ISSUE THREAD

**Issue by taikn** [webpack-contrib/webpack-hot-client#60]
* Operating System: macOS 10.13.4
* Node Version: 8.10.0
* NPM Version: 5.80
* webpack Version: 4.8.2
* webpack-hot-client Version: 3.0.0

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Description

I am using `webpack-hot-client` together with `webpack-serve`. Now with version 3.0.0 being out and #53 and #58 merged, how can one configure webpack-hot-client to have a client per entry as opposed to only one client per all entries? Would be great to have it mentioned somewhere in the README

**Comment by taikn** [comment]
:ok_hand: My use case is actually pretty simple, I have two entry points resulting in two separate pages - lets call these `page A` and `page B`, now when I work with the `page A` - Websocket is connected and updates are flawlessly delivered to the browser, while accessing `page B` works as expected, doing some changes to the actual code leaves me pretty much hitting <kbd>CMD</kbd>+<kbd>R</kbd> in the browser to see the updates.

**Comment by shellscape** [comment]
Interesting. Can you paste your webpack config?

**Comment by taikn** [comment]
For my webpack config I am utilising composable configuration described in Juho's [Webpack Book](https://survivejs.com/webpack/).
There is `webpack.parts.js` where the small function-based interfaces are defined and amongst them
function to initialise pages:

```javascript
...

const HtmlWebpackPlugin = require('html-webpack-plugin')

exports.page = ({
    path = '',
    template = require.resolve(
      'html-webpack-plugin/default_index.ejs'
    ),
    title,
    entry,
    chunks
  } = {}
) => ({
  entry,
  plugins: [
    new HtmlWebpackPlugin({
      chunks,
      filename: `${path && path + '/'}index.html`,
      template,
      title
    })
  ]
})

...

```

And then there is a higher level configuration stored in `webpack.config.js`, 
where the final config is being merged based on `env` variable

```javascript

const path = require('path')
const merge = require('webpack-merge')
const parts = require('./webpack.parts')

...

const PATHS = {
  src: path.join(__dirname, 'src')
}

const commonConfig = merge([ ... ])
const productionConfig = merge([ ... ])
const developmentConfig = merge([ ... ])

...

module.exports = () => {
  const mode = process.env.NODE_ENV

  const pages = [
    parts.page({
      title: 'Page A',
      entry: {
        pageA: [
          'babel-polyfill',
          'blueimp-canvas-to-blob',
          'whatwg-fetch',
          PATHS.src
        ]
      },
      chunks: ['pageA', 'manifest', 'vendor'],
      template: 'template.html'
    }),
    parts.page({
      title: 'Page B',
      path: 'lp',
      entry: {
        pageB: [
          'babel-polyfill',
          path.join(PATHS.src, 'lp.js')
        ]
      },
      chunks: ['pageB', 'manifest', 'vendor'],
      template: 'template.html'
    })
  ]

  const config =
    mode === 'production'
      ? productionConfig
      : developmentConfig

  return merge([commonConfig, config, { mode }].concat(pages))
}

```

**Comment by shellscape** [comment]
OK can you merge what the result of that is? That's what I'll need to see to grasp what you're trying to accomplish.

**Comment by taikn** [comment]
sure, this is how merged result looks like:

```javascript
{
  output: {
    path: '/.../build',
    publicPath: '/'
  },
  resolve: {
    modules: ['/.../src', 'node_modules']
  },
  module: {
    rules: [[Object], [Object], [Object]]
  },
  plugins: [{ apply: [Function: apply] },
    DefinePlugin { definitions: [Object] },
    CircularDependencyPlugin { options: [Object] },
    HtmlWebpackPlugin { options: [Object] },
    HtmlWebpackPlugin { options: [Object] }],
  devtool: 'source-map',
  serve: {
    add: [Function: add]
  },
  mode: 'development',
  entry: {
    pageA: [
      'babel-polyfill',
      'blueimp-canvas-to-blob',
      'whatwg-fetch',
      '/.../src'
    ],
    pageB: [
      'babel-polyfill',
      '/.../src/lp.js'
    ]
  }
}
```

where `options` for the first HtmlWebpackPlugin entry look like:

```javascript
options: {
  template: 'template.html',
  filename: 'index.html',
  hash: false,
  inject: true,
  compile: true,
  favicon: false,
  minify: false,
  cache: true,
  showErrors: true,
  chunks: ['pageA', 'manifest', 'vendor'],
  excludeChunks: [],
  chunksSortMode: "auto",
  meta: {},
  title: "Page A",
  xhtml: false
}
```

**Comment by shellscape** [comment]
OK and I'm assuming the second `HtmlWebpackPlugin` works with `chunks: ['pageB'....` - is that correct?

**Comment by taikn** [comment]
Precisely!

**Comment by shellscape** [comment]
Ah, OK. Using chunks that way isn't something we anticipated. I believe the typical route there is to export an array of compiler configs, so that's not one I saw coming. We'll need to implement a new feature to allow for that. Probably an `allEntries` boolean option that will apply it to all entries in a compiler. I'm going to wager that won't be frequently used, but the use-case is there and is solid.

In the mean time, you can configure that manually. If you get stuck let me know and I'll help there. It's likely going to be at least two weeks until that feature will land.

**Comment by shellscape** [comment]
Your entry should look like this: https://github.com/webpack-contrib/webpack-hot-client/blob/276d9509577b8edd4df8e8d259a4a0ecf40efa3f/lib/util.js#L10

```js
`webpack-hot-client/client?compilerName`
```

**Comment by shellscape** [comment]
@taikn please see #64 and #65

**Comment by lastnigtic** [comment]
can someone give an example about how to deal with this problem,I'm just stuck in this issue. thanks
