### ISSUE TITLE
Browser keeps refreshing with multiple entry points/configurations

### ISSUE THREAD

**Issue by ematipico** [webpack-contrib/webpack-hot-client#61]
* Operating System: Windows 7
* Node Version: 6.10
* NPM Version: 5.3.0
* webpack Version: 4.6.0
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
This the `webpack-serve` API code.

```js
const config = require('webpack.config')
serve({
 config,
 logLevel: 'trace',
 dev: {
   publichPath: '/'
 },
 add: (app, middleware) => {
   middleware.webpack();
   middleware.content({
      index: 'index.html'
   });
 }
});
```

##### webpack.config.js

```js
module.exports = [
  {
     entry: {
       index: [path.resolve(__dirname, 'app.js')],
     },
     mode: 'development',
     output: {
       filename: 'output.js',
     }
  }
  {
     entry: {
       index: [path.resolve(__dirname, 'iframe-app.js')],
     },
     mode: 'development',
     output: {
       filename: 'iframe-bundle.js',
     }
  }
]
```

```html
<!-- index.html from where I serve my bundles -->

<html>
  <body>
      <iframe src="http://localhost:8080/iframe.html">

      </iframe>
     <script src="output.js"></script>
  </body>
</html>
```

```html
<!-- iframe.html where I load the second bundle -->

  <div>
     <script src="iframe-bundle.js"></script>
  </div>
```

### Expected Behavior

It should serve both bundles without refreshing the whole web page.

### Actual Behavior

The browsers keeps refreshing every time the iframe gets rendered and loads the second output.

### How Do We Reproduce?

I managed to have the same 'refreshing loop' by having two entry points that are loaded in the same page or by recreating a situation like mine (which could take longer).

**Comment by shellscape** [comment]
Not sure how to fix this one to be honest. We'll probably need a minimum-reproducible repo to work on. This line https://github.com/webpack-contrib/webpack-hot-client/blob/master/index.js#L186 as well as this line https://github.com/webpack-contrib/webpack-hot-client/blob/276d9509577b8edd4df8e8d259a4a0ecf40efa3f/lib/client/index.js#L7-L9 should have prevented that from happening.
