### ISSUE TITLE
Drop (revert) `allEntries` option in favor `autoConfigure`

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/webpack-hot-client#67]
* Operating System: Ubuntu 18.04
* Node Version: 10.2.1
* NPM Version: 6.1.0
* webpack Version: 4.10.0
* webpack-hot-client Version: 3.0.0

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code

i think not required

### Expected Behavior

We implement `allEntries` option (but not released). After spend a lot of time on migration from `webpack-dev-server` to `webpack-serve` in many projects (i use git version and build script, because i needed add hot client not only first entry point) i found this option is misleading and unnecessary.

We already have `autoConfigure` option and we can implement more universal solution:
1. `autoConfigure: true` (maybe add alias `first`) - mean modify only first entry (as works right now).
2. `autoConfigure: 'all` - modify all `entries`.
3. `autoConfigure: ['list', 'of', 'entries']` - modify only entries which in array.

This values of option are enough in 99% use case. Also no new option and more universal solution.

### Actual Behavior

`allEntries` configure only all entry points. Also no easy solution to configure list of `entries`.

### For Bugs; How can we reproduce the behavior?

not the bug

### For Features; What is the motivation and/or use-case for the feature?

not the feature

**Comment by shellscape** [comment]
I disagree with your assessment. Two boolean options is inherently simpler and less complex than a single option with multiple potential values, with an infinite number of potential requested values. As `allEntries` will in all likelihood be seldom-used unless chunks are being manipulated, a straightforward option is preferred.

**Comment by evilebottnawi** [comment]
@shellscape I disagree too. A lot of configs contain not only one entry point, also may values in `webpack` have same values. Example `splitChunks.chunks` can contain `initial`, `async` `all`, array and function, it is enoght in 99% use case. Example i maintaner `WordPress` and we have around 15+ entry points, some of them require hot client some not, solution with array solve our problems without big stupid configuration.

**Comment by evilebottnawi** [comment]
@shellscape Why not `entries: all` or `entries: []` instead `allEntries`? `allEntries` is really strange. When you have one entry point you don't require `allEntries`, but when you have many entrypoint (very very othen part of their do not require for hot client) you should write bug config around where add hot client, where not. What we need `allEntries` if this does not solve easy configuration in most cases :confused:

**Comment by evilebottnawi** [comment]
Or we can rename `allEntries` to `entries` with only two values `true` and `function` It is solve all problem with big and complex configuration

**Comment by shellscape** [comment]
(Use the edit button please)

What you're proposing is more complex and honestly more confusing. I do not believe that your proposal is good architecture. Users have three courses of action:

1. default behavior - first entry in each compiler configuration
2. all entries in each compiler configuration
3. manual configuration

If users need more than 1 or 2, or they need something more custom, they can turn off auto config and set it up themselves for full control. What you are proposing is the old approach of do-everything-and-try-to-anticipate-every-need-of-the-user-ever that got webpack-dev-server into trouble. We've written in stone the three different choices users have, with the last being empowerment of the user to use whatever setup they want to, manually. That's enough flexibility, and minimizes complexity in the module.

That's all we need.

**Comment by evilebottnawi** [comment]
@shellscape hm, okey, let's leave this as is, when wait release new version with `allEntries` option? (in same case it is very comfortable).

**Comment by ZSkycat** [comment]
I wasted a night because allEntries defaults to false. QAQ

**Comment by shellscape** [comment]
Bummer. It's right there in the documentation too: https://github.com/webpack-contrib/webpack-hot-client#allentries

**Comment by ZSkycat** [comment]
Because I am not using `webpack-hot-client` directly.
When the `webpack-serve` is updated, I don't know that there is such a change.
Just a little do not understand why the default value is not `true`.
Anyway, I successfully solved my problem.
