### ISSUE TITLE
Build time reported by webpack always has 11 seconds added to it

### ISSUE THREAD

**Issue by eddiesholl** [webpack-contrib/webpack-hot-client#68]
* Operating System: macos
* Node Version: v8.5.0
* NPM Version: 5.3.0
* webpack Version: 4.9.1
* webpack-serve Version: 1.0.2

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

Repo is available at https://github.com/eddiesholl/webpack-timing-bug

### Expected Behavior
Continuing discussion from https://github.com/webpack-contrib/webpack-serve/issues/152.

The build time reported by webpack should be correct.

### Actual Behavior

When webpack runs inside `webpack-serve`, the build time reported by webpack is 11 seconds longer than it should be, because `react-hot-client` is pushing the startTime back by 11 seconds at https://github.com/webpack-contrib/webpack-hot-client/blob/5cc12b7f7ac8f3a529e409819af02f4f4d82a380/index.js#L112.

This is a fix/hack to try to avoid issues when watching files that have been created recently. There is a solution in place in `webpack-serve` to use `time-fix-plugin` to roll this time back and then forward again, which should hopefully end up with the correct startTime in place. But this explicit rollback here in `react-hot-client` will always push the value out, it is not cleaned up anywhere. It needs a symmetrical roll forward of the startTime.

### For Bugs; How can we reproduce the behavior?
Repo linked above with simple reproduction steps.

**Comment by noe132** [comment]
yeah, I got this extra large time issue too

**Comment by shellscape** [comment]
Folks, it's purely a cosmetic display issue. Your build times are not actually 10s longer. We'll circle back to this when we have the chance.

**Comment by shellscape** [comment]
This was resolved as a side effect of #70
