### ISSUE TITLE
`allEntries: true` only configures the first entry

### ISSUE THREAD

**Issue by calvinl** [webpack-contrib/webpack-hot-client#76]
* Operating System: MacOS 10.13.4
* Node Version: v9.10.1
* NPM Version: 6.1.0
* webpack Version: 4.10.2
* webpack-hot-client Version: 3.0.0

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
  entry: {
    app: ['./client/app'],
    admin: ['./client/admin']
  }
  // ...
```

```js
// Using webpack-serve
serve({
  config: require('./webpack.config.js'),
  host: 'localhost',
  port: '3000',
  logLevel: 'debug',
  // options passed to webpack-hot-client
  hot: {
    allEntries: true,
    autoConfigure: true
  },
  dev: {
    publicPath: '/',
    headers: { 'Access-Control-Allow-Origin': '*' },
    stats: {
      colors: true,
      children: false
    }
  }
});
```

### Expected Behavior

`webpack-hot-client` is configured with both entry points, `app` and `admin`. 

### Actual Behavior

`webpack-hot-client` is only configured with the first entry: 

```
 [0] multi ./client/app 28 bytes {app} [built]
[14] multi ./client/admin 28 bytes {admin} [built]
[17] multi webpack-hot-client/client?b068869c-deaf-4240-811a-b153750bcbd8 ./client/app 40 bytes {app} [built]
```

If I switch the entry points around, like so:
```js
  // webpack.config.js
  entry: {
    admin: ['./client/admin'],
    app: ['./client/app']
  }
  // ...
```

Then only the admin entry point is enabled:
```
 [0] multi ./client/admin 28 bytes {admin} [built]
 [9] multi ./client/app 28 bytes {app} [built]
[17] multi webpack-hot-client/client?5b77d4a2-d4cd-490c-aa0a-9f704bf2f2be ./client/admin 40 bytes {admin} [built]
```

### For Bugs; How can we reproduce the behavior?

See above?

### For Features; What is the motivation and/or use-case for the feature?

To have HMR enabled on both entry points (main app and admin app).

**Comment by calvinl** [comment]
Apologies - I just read the release notes for the breaking change in 3.0.0 for this, so this isn't really a "bug". 

However, what would be a suitable workaround for my situation in which I have multiple bundles, used on separate pages?

**Comment by shellscape** [comment]
If you're stuck on v3.x (like the current version of `webpack-serve` is at the moment) you can use `autoConfigure: false` and manually setup the entries and the HMR plugin. If using `webpack-serve` can revert to < v1.0.0. If using this module separately revert to < v3.0.0.

**Comment by calvinl** [comment]
@shellscape Thanks for the info! Are there any examples of manual configuration? It’s not really clear.

**Comment by shellscape** [comment]
Yeah it's not really intended to be used with this module, as auto-configuration is preferred to prevent goof-ups. Your entries should all be an `Array` in the end, and should have a first item that looks like this: https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/compiler.js#L9

And then add a `HotModuleReplacementPlugin` to plugins manually in your config.
