### ISSUE TITLE
Feature Request: Support Filtering Warnings

### ISSUE THREAD

**Issue by treylon** [webpack-contrib/webpack-hot-client#78]
* Operating System: N/A
* Node Version :N/A
* NPM Version: N/A
* webpack Version: N/A
* webpack-hot-client Version: 4.0.3

- [ ] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### What is the motivation and/or use-case for the feature?

Webpack supports filtering warnings by default using the stats field in the configuration object, which is very neat on some use-cases. It would be nice if the webpack-hot-client would also support this pattern and not just a flag for enabling/disabling warnings and errors in general.
Documentation for stats describing : [https://webpack.js.org/configuration/stats/](https://webpack.js.org/configuration/stats/)
Implementation in webpack: [ https://github.com/webpack/webpack/blob/949890acdf1d00d9e53054b56ad3e7215215416d/lib/Stats.js#L26 ](https://github.com/webpack/webpack/blob/949890acdf1d00d9e53054b56ad3e7215215416d/lib/Stats.js#L26)

**Comment by shellscape** [comment]
_Please don't edit or remove sections of the issue template._

This module uses the `stats` object as provided by webpack to consumers of the various hooks that it exposes. This probably won't be a high priority for us anytime soon. We'll leave it open for a month to see if it gains any support. If it does get a large amount of support, we may choose to increase its priority. If it's something that can be remedied or implemented within this module, and a Pull Request is opened from the community, we'll review the changes.

**Comment by shellscape** [comment]
Closing as stale. If discussion picks up we'll reopen.

**Comment by davidkudera** [comment]
Hi, I come across this issue because of https://github.com/angular/angular/issues/21560.

It seems that completely disabling all warnings doesn't work either. If I debugged the code correctly the problem is here: https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/index.js#L33

The `stats` option defined by me is being overwritten by another object.
