### ISSUE TITLE
TypeError: Cannot read property 'beforeCompile' of undefined

### ISSUE THREAD

**Issue by Sawtaytoes** [webpack-contrib/webpack-hot-client#82]
* Operating System: Windows 10 64-bit
* Node Version: 8.11.2
* NPM Version: yarn 1.6.0
* webpack Version: 3.11.0
* webpack-hot-client Version: 4.0.4

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
  modifyCompiler(compiler, options) {
    for (const comp of [].concat(compiler.compilers || compiler)) {
      // since there's a baffling lack of means to un-tap a hook, we have to
      // keep track of a flag, per compiler indicating whether or not we should
      // add a DefinePlugin before each compile.
      comp.hotClient = { optionsDefined: false };

      comp.hooks.beforeCompile.tap('WebpackHotClient', () => {
        if (!comp.hotClient.optionsDefined) {
          comp.hotClient.optionsDefined = true;
```

Looking at this code, it creates a brand new array, then tries to do `comp.hooks.beforeCompile` on that array. Since there's no null-propagation, it will error because `hooks` hasn't yet been defined on that array.

### Expected Behavior
I can run Express without this erroring.

### Actual Behavior
I receive an error:
```js
TypeError: Cannot read property 'beforeCompile' of undefined
    at modifyCompiler (webpack-hot-client\lib\compiler.js:136:18)
    at module.exports (webpack-hot-client\lib\index.js:22:3)
    at Object.<anonymous> (scripts\server\develop\getHttpServerConfig.js:20:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (scripts\server\develop\index.js:1:91)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
i ｢hot｣: WebSocket Server Listening on localhost:56699
```

### For Bugs; How can we reproduce the behavior?
Call `webpackHotClient` and pass the `webpackCompiler` object.
```js
webpackHotClient(webpackCompiler)
```

### For Features; What is the motivation and/or use-case for the feature?
N/A

**Comment by shellscape** [comment]
Thanks for the issue :beer:

Unfortunately you missed the part at the top of the README that states that [this module requires webpack v4 or higher](https://github.com/webpack-contrib/webpack-hot-client#requirements). The `peerDependency` for webpack also states at least the same version or higher.

**Comment by Sawtaytoes** [comment]
But this issue is going to error with any version right?

Either way, I looked back and saw that line under Requirements. The part that had me questioning it is this:
> For users of webpack v4+ that go the zero-config route, you must specify an entry option.
If it's required, everyone would then be using Webpack v4+.

**Comment by shellscape** [comment]
> But this issue is going to error with any version right? I guess, only if that code block is hit.

Not so. `hooks` is part of every `Compiler` and `MultiCompiler`. See https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L33
