### ISSUE TITLE
Client port ignored

### ISSUE THREAD

**Issue by MatTheCat** [webpack-contrib/webpack-hot-client#86]
* Operating System: Alpine 3.7.0
* Node Version: 10.6.0
* NPM Version: 6.1.0
* webpack Version: 4.15.1
* webpack-hot-client Version: 4.1.0

### Expected Behavior

Websocket client uses client port.

### Actual Behavior

Websocket client try using server port.

![](https://user-images.githubusercontent.com/1898254/42503601-63e71d72-8439-11e8-84d2-f3c479290b89.png)

### Code

```console
  $ webpack-serve docs/webpack.config.js
```

##### serve.config.js

```js
module.exports = {
  clipboard: false,
  devMiddleware: {
    publicPath: '/pattern-library/dist/'
  },
  hotClient: {
    allEntries: true,
    host: {
      client: '*',
      server: '127.0.0.1'
    },
    port: {
      client: 8082,
      server: 8081
    }
  },
  host: '0.0.0.0'
}
```

### How Do We Reproduce?

Set `hotClient.port` as an object with different ports for `client` and `server`.

I tracked the issue until [modifyCompiler](https://github.com/webpack-contrib/webpack-hot-client/blob/v4.1.0/lib/compiler.js#L129). `options.webSocket` changes between the function call and `beforeCompile` event. No idea why.

**Comment by MatTheCat** [comment]
Maybe the culprit is https://github.com/webpack-contrib/webpack-hot-client/blob/v4.1.0/lib/socket-server.js#L107

**Comment by shellscape** [comment]
Indeed. That and a few other spots. The logic is sneaky for that option.
