### ISSUE TITLE
`warningsFilter` is not honoured

### ISSUE THREAD

**Issue by OliverJAsh** [webpack-contrib/webpack-hot-client#94]
* Operating System: macOS 10.13.5
* Node Version: 9.8.0
* NPM Version: 5.10.0
* webpack Version: 4.12.0
* webpack-hot-client Version: 4.1.1

### Expected Behavior

webpack's [`stats.warningsFilter`] should be honoured in the log output of `webpack-hot-client`.

### Actual Behavior

webpack's [`stats.warningsFilter`] is not honoured in the log output of `webpack-hot-client`.

### Code

```js
{
  stats: {
    warningsFilter: /export .* was not found in/
  }
}
```

![image](https://user-images.githubusercontent.com/921609/43142862-4997743a-8f51-11e8-8070-ed6033c8e272.png)

### How Do We Reproduce?

Define a [`stats.warningsFilter`] and observe the log output.

[`stats.warningsFilter`]: https://webpack.js.org/configuration/stats/

**Comment by shellscape** [comment]
`stats` has no bearing on the output in the browser's development console. Use the [`logLevel`](https://github.com/webpack-contrib/webpack-hot-client#loglevel) option if you want to change that.

**Comment by OliverJAsh** [comment]
I guess we need a similar option to `stats.warningsFilter` for browser logs? We would like a way to *filter* the warnings, not hide them completely.

**Comment by shellscape** [comment]
That would be a lot of unneeded complexity for minutia around displaying logs in the browser. Just keep an eye on your terminal and you'll only see there what you want to see, as `webpack-dev-middleware` displays output from a compilation based on stats. Adding anything like `stats` for the browser console in this module is not something likely to happen unless there was a call for it by thousands of users.

**Comment by JounQin** [comment]
It is also needed for Angular project to filter `System.import` warnings for now.
https://github.com/angular/angular/issues/21560#issuecomment-406342840

**Comment by Benno007** [comment]
@JounQin same here - just came from that ticket, thanks for linking it. We use an angular project using webpack 4 and angular 5, with webpack dev server and we are also seeing 4 of those System.import logs on each page load. Had to up our client-log-level in webpack-dev-server to error only to prevent these errors (from HMR) logging to the browser console.

**Comment by lehni** [comment]
The problem with setting `logLevel: 'error'` is that is also silences all info. It would be nice to hav a way to only disable warnings but keep info and errors.

I thiknk I found a way to hide warnings that doesn't also silence info, by using the following: 

```js
send: {
  warnings: false
}
```

This omits any warnings that are sent through the socket.

**Comment by lehni** [comment]
Ok while the above actually works, it turns of the call of `reload()`. This seems a strange unwanted side-effect of the `send.warnings` option?

But looking at the code, I understand why it's happening:

### `lib/socket-server.js`:
```js
  if (warnings.length > 0) {
    if (options.send.warnings) {
      send('warnings', { warnings });
    }
  } else {
    send('ok', { hash });
  }
```

And `warnings()` is defined as:

### `lib/client/index.js`:
```js
    warnings({ warnings }) {
      log.warn('Warnings while compiling.');
      … 
      reload();
    },
```

So not sending warnings also doesn't call `reload()`.

This looks like it would need something like this to work as expected?


```js
  if (warnings.length > 0 && options.send.warnings) {
    send('warnings', { warnings });
  } else {
    send('ok', { hash });
  }
```
